esphome:
  name: flower-enviroment
  platform: ESP8266
  board: nodemcuv2
#  includes:
#    - custom/mlx90614.h
#  libraries:
#    - "Adafruit MLX90614 Library"

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
 password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Flower-Enviroment"
    password: !secret esphome_fallback_password

#i2c:
#  sda: GPIO4
#  scl: GPIO5
#  scan: True
#  id: bus_a
#  frequency: 50kHz
  
sensor:
#  - platform: custom 
#    lambda: |-
#      auto mlx = new MLX90614(5000);   
#      App.register_component(mlx);
#      return {mlx->ambient_temperature_sensor, mlx->object_temperature_sensor};
#    sensors:
#    - name: "Flower Ambient Temperature"
#      unit_of_measurement: °C
#      accuracy_decimals: 1
#    - name: "Flower Leaf Temperature"
#      unit_of_measurement: °C
#      accuracy_decimals: 1
#  - platform: adc
#    pin: A0
#    name: "Soil Moisture Level"
#    update_interval: 5s
#    unit_of_measurement: "%"
#    filters:
#    - median:
#        window_size: 7
#        send_every: 4
#        send_first_at: 1
#    - calibrate_linear:
#        - 0.81 -> 0.00
#        - 0.42 -> 100.00
#    - lambda: if (x < 1) return 0; else return (x);
#    accuracy_decimals: 0

  - platform: dht
    pin: GPIO10
    model: DHT22_TYPE2
    temperature:
      name: "Flower Temperature"
    humidity:
      name: "Flower Humidity"
    update_interval: 30s
    
  - platform: adc
    pin: A0
    name: "Flower CO2"
    accuracy_decimals: 0
    update_interval: 10s
    unit_of_measurement: "ppm"
    filters:
     - calibrate_linear:
          - 0.79004 -> 190
          - 0.61816 -> 1603

switch:
  - platform: gpio
    pin: D0
    inverted: true
    name: "RO Supply"
  - platform: gpio
    pin: D1
    inverted: true
    name: "Storage Circulation"
    restore_mode: ALWAYS_ON
  - platform: gpio
    pin: D2
    inverted: true
    name: "Nutriant Fill"
  - platform: gpio
    pin: D3
    inverted: true
    name: "Storage to Waste"
  - platform: gpio
    pin: D4
    inverted: true
    name: "Switch D4"
  - platform: gpio
    pin: GPIO9
    inverted: true
    name: "Switch D5"
  - platform: gpio
    pin: D6
    inverted: true
    name: "Switch D6"
  - platform: gpio
    pin: D7
    inverted: true
    name: "Switch D7"
  - platform: gpio
    name: "Switch D8"
    pin: D8
  - platform: gpio
    name: "flower dehumidifier"
    pin: GPIO3
#    inverted: true

    
output:
  - platform: esp8266_pwm
    pin: D5
    frequency: 3000 Hz
    id: flowerlightoutput
    
light:
  - platform: monochromatic
    name: "Flower LED's"
    output: flowerlightoutput
    gamma_correct: 1.0