esphome:
  name: left-soil-moisture
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
 password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Left-Soil-Moisture"
    password: !secret esphome_fallback_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO36
    name: "Soil Moisture Left Back"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - median:
        window_size: 3
        send_every: 1
        send_first_at: 1
    - calibrate_linear:
        - 1.1630 -> 100.00
        - 2.2390-> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: GPIO39
    name: "Soil Moisture Left Middle"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - median:
        window_size: 3
        send_every: 1
        send_first_at: 1
    - calibrate_linear:
        - 1.4880 -> 100.00
        - 2.5890 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: GPIO34
    name: "Soil Moisture Left Front"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
    - median:
        window_size: 3
        send_every: 1
        send_first_at: 1
    - calibrate_linear:
        - 1.2480 -> 100.00
        - 2.1880 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0