esphome:
  name: left-soil-moisture
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "af778b524477d7905a17690b9509d2f0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Left-Soil-Moisture"
    password: !secret esphome_fallback_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO36
    name: "Soil Moisture Left Back"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
#    - median:
#        window_size: 3
#        send_every: 1
#        send_first_at: 1
    - calibrate_linear:
        - 1.42 -> 100.00
        - 1.99-> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: GPIO39
    name: "Soil Moisture Left Middle"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
#    - median:
#        window_size: 3
#        send_every: 1
#        send_first_at: 1
    - calibrate_linear:
        - 1.70 -> 100.00
        - 2.76 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0

  - platform: adc
    pin: GPIO34
    name: "Soil Moisture Left Front"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
#    - median:
#        window_size: 3
#        send_every: 1
#        send_first_at: 1
    - calibrate_linear:
        - 1.30 -> 100.00
        - 2.27 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0