esphome:
  name: veg-enviroment
  platform: ESP32
  board: esp32dev

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: !secret esphome_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Left-Soil-Moisture"
    password: !secret esphome_fallback_password

captive_portal:

sensor:
  - platform: adc
    pin: GPIO36
    name: "Veg Soil Moisture"
    update_interval: 10s
    unit_of_measurement: "%"
    attenuation: 11db
    filters:
#    - median:
#        window_size: 3
#        send_every: 1
#        send_first_at: 1
    - calibrate_linear:
        - 1.16 -> 100.00
        - 2.32 -> 0.00
    - lambda: if (x < 1) return 0; else return (x);
    accuracy_decimals: 0
    
  - platform: dht
    pin: GPIO5
    model: DHT22_TYPE2
    temperature:
      name: "Veg Temp"
    humidity:
      name: "Veg Humidity"
    update_interval: 30s